# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST http://localhost:8080/products
Content-Type: application/json 

{
    "name": "Beer Is Good Food",
    "sku": "beer-1",
    "QtyOnHand": 12,
    "costPerUnit": -8.99
}